Repository tomochain/tomoscan, pull requests merged in 2018-07, with the labels that each got.

#224 Add CD/CI pipeline
  .travis.yml
  Dockerfile.client
  Dockerfile.server
  docker_push.sh
  docker_rebuild.sh
Labels: CI/CD

#246 Add pipeline for tagged release
  .travis.yml
  docker_push.sh
Labels: CI/CD

#247 Fix missing check repo check for PR
  .travis.yml
Labels: CI/CD

#248 fix #233
  client/assets/scss/components/_card.scss
  client/assets/scss/components/_contract-info.scss
  client/components/ReadContract.vue
  client/components/TableTokenTx.vue
  client/components/TableTx.vue
  client/components/TableTxByAccount.vue
  client/pages/address/_slug.vue
  client/pages/blocks/_slug.vue
  client/pages/blocks/index.vue
  client/pages/contracts/index.vue
  client/pages/txs/_slug.vue
  server/src/api/ContractController.js
Labels: review

#249 Fix travis build stage
  .travis.yml
  docker_push.sh
  docker_rebuild.sh
Labels: CI/CD, bug, review

#250 Update .travis.yml
  .travis.yml
Labels: CI/CD, bug, review
